apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-appset
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - clusters: {}
        - git:
            repoURL: 'https://github.com/Waji-97/HomeLab.git'
            revision: 'main'
            directories:
              - path: '../../components/**/*'
  template:
    metadata:
      name: '{{.name}}-{{path}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Waji-97/HomeLab.git'
        targetRevision: 'main'
        path: '{{path}}'
      destination:
        server: '{{.server}}'
        namespace: 'argocd'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true