apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./alertmanager-alertmanager.yaml
- ./alertmanager-podDisruptionBudget.yaml
# - ./alertmanager-secret.yaml
- ./alertmanager-service.yaml
- ./alertmanager-serviceAccount.yaml
- ./alertmanager-serviceMonitor.yaml

patches:
  - target:
      group: monitoring.coreos.com
      kind: Alertmanager
      name: main
    path: alertmanager-patch.yaml