apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-homelab
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wajiwos14@gmail.com
    privateKeySecretRef:
      name: letsencrypt-homelab-account-key
    solvers:
      - http01:
          ingress:
            class: nginx