apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- ns.yaml

helmCharts:
- name: ingress-nginx
  includeCRDs: true
  valuesInline:
    controller:
      service:
        type: LoadBalancer
      extraArgs:
        default-ssl-certificate: "ingress-nginx/ingress-tls"
  releaseName: ingress-nginx
  version: 4.12.0
  repo: https://kubernetes.github.io/ingress-nginx