apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- ingress-resources.yaml

helmCharts:
- name: ingress-nginx
  namespace: ingress-nginx
  includeCRDs: true
  valuesInline:
    controller:
      allowSnippetAnnotations: true
      config:
        annotations-risk-level: Critical
      service:
        type: LoadBalancer
      extraArgs:
        default-ssl-certificate: "ingress-nginx/ingress-tls"
      extraVolumeMounts:
        - mountPath: /etc/apache2
          name: auth
      extraVolumes:
        - secret:
            secretName: basic-auth
            defaultMode: 420
            items:
            - key: auth
              path: auth
          name: auth
  releaseName: ingress-nginx
  version: 4.12.0
  repo: https://kubernetes.github.io/ingress-nginx