apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: cert-manager-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Waji-97/HomeLab.git'
    targetRevision: 'main'
    path: 'kubernetes/components/cert-manager'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true