apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: homelab-post
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Waji-97/HomeLab.git'
    targetRevision: 'main'
    path: 'kubernetes/deployments/post'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: ServiceMonitor
      jqPathExpressions:
      - .metadata.annotations
    - group: monitoring.coreos.com
      kind: Prometheus
      jqPathExpressions:
      - .spec.remoteWrite[]?.writeRelabelConfigs[]?.action
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
      jqPathExpressions:
      - .rules[] | select (.apiGroups == ["discovery.k8s.io"])