apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: kube-prometheus-stack
  includeCRDs: true
  valuesInline:
    prometheusOperator:
      admissionWebhooks:
        enabled: false
      tls:
        enabled: false
    fullnameOverride: "prometheus-stack"
    defaultRules:
      create: false
    grafana:
      enabled: true
      persistence:
        enabled: true
        type: pvc
        storageClassName: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 8Gi
        finalizers:
          - kubernetes.io/pvc-protection
    alertmanager:
      alertmanagerSpec:
        # useExistingSecret: true
        # configSecret: "alertmanager-prometheus-stack-alertmanager-main"
        replicas: 1
        storage: 
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 4Gi
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: true
    prometheus:
      agentMode: false
      thanosService:
        enabled: true
      thanosServiceMonitor: 
        enabled: true
      prometheusSpec:
        # remoteWrite:
        # - url: http://kube-thanos-receive:19291/api/v1/receive
        #   #enableHTTP2: false
        disableCompaction: true
        externalLabels:
          cluster: homelab.local
        retention: 7d
        replicas: 1
        shards: 2
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
            selector: {}
  releaseName: kube-prometheus-stack
  version: 69.6.0
  repo: https://prometheus-community.github.io/helm-charts

patchesJson6902:
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheusagents.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: alertmanagerconfigs.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: scrapeconfigs.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"