all:
  hosts:
    mini1:
      ansible_host: 192.168.219.200
      ip: 192.168.219.200
      access_ip: 192.168.219.200
    mini2:
      ansible_host: 192.168.219.201
      ip: 192.168.219.201
      access_ip: 192.168.219.201
    mini3:
      ansible_host: 192.168.219.202
      ip: 192.168.219.202
      access_ip: 192.168.219.202
    rel:
      ansible_host: 192.168.219.199
      ip: 192.168.219.199
      access_ip: 192.168.219.199
  children:
    kube_control_plane:
      hosts:
        mini1:
        mini2:
        mini3:
    kube_node:
      hosts:
        rel:
    etcd:
      hosts:
        mini1:
        mini2:
        mini3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
