apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml

helmCharts:
- name: openebs
  namespace: openebs
  includeCRDs: true
  valuesInline:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
  releaseName: openebs
  version: 4.2.0
  repo: https://openebs.github.io/openebs