apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
- ns.yaml

helmCharts:
- name: longhorn
  includeCRDs: true
  valuesInline:
    preUpgradeChecker:
      jobEnabled: false
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
  releaseName: longhorn
  version: v1.8.0
  repo: https://charts.longhorn.io/