apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  k8s-app: metrics-server
resources:
  - apiservice.yaml
  - deployment.yaml
  - rbac.yaml
  - service.yaml

patches:
  - target:
      version: apps/v1
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      version: apps/v1
      kind: APIService
      name: metrics-server
    patch: |-
      - op: replace
        path: /spec/service/namespace
        value: monitoring
  - target:
      version: apps/v1
      kind: ServiceAccount
      name: metrics-server
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
  - target:
      version: apps/v1
      kind: RoleBinding
      name: metrics-server-auth-reader
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
      - op: replace
        path: /subjects/0/namespace
        value: monitoring
  - target:
      version: apps/v1
      kind: ClusterRoleBinding
      name: metrics-server:system:auth-delegator
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: monitoring
  - target:
      version: apps/v1
      kind: ClusterRoleBinding
      name: system:metrics-server
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: monitoring
  - target:
      version: apps/v1
      kind: Service
      name: metrics-server
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
